INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adrian@ejemplo.com', 'Consulta sobre instalación de placas solares.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Laura', 'Martínez', 'laura.martinez@ejemplo.com', 'Necesito asesoramiento sobre sistemas de alarmas.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Carlos', 'González', 'carlos.gonzalez@ejemplo.com', 'Información sobre la instalación de cámaras de seguridad.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Ana', 'López', 'ana.lopez@ejemplo.com', '¿Qué tipos de iluminación LED ofrecen?');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('José', 'Fernández', 'jose.fernandez@ejemplo.com', 'Quiero saber más sobre las antenas parabólicas.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('María', 'Sánchez', 'maria.sanchez@ejemplo.com', 'Estoy interesado en instalar aire acondicionado en mi casa.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Pedro', 'Pérez', 'pedro.perez@ejemplo.com', 'Consulta sobre instalación de cableado para red de antenas.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Beatriz', 'Gutiérrez', 'beatriz.gutierrez@ejemplo.com', '¿Cómo funciona la instalación de leds RGB?');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Luis', 'Ramírez', 'luis.ramirez@ejemplo.com', 'Interesado en la instalación de sistemas de seguridad volumétricos.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Marta', 'Díaz', 'marta.diaz@ejemplo.com', 'Consulta sobre instalación de sistemas de cámaras de seguridad.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Javier', 'Jiménez', 'javier.jimenez@ejemplo.com', 'Necesito presupuesto para la instalación de placas solares.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Patricia', 'Gómez', 'patricia.gomez@ejemplo.com', 'Asesoría sobre sistemas de iluminación RGB para exterior.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Iván', 'Martínez', 'ivan.martinez@ejemplo.com', '¿Cuáles son las opciones de cámaras de seguridad para casas?');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Susana', 'Hernández', 'susana.hernandez@ejemplo.com', 'Me gustaría saber más sobre los servicios de electricidad.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Francisco', 'Álvarez', 'francisco.alvarez@ejemplo.com', 'Presupuesto para instalación de antenas parabólicas.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Carmen', 'García', 'carmen.garcia@ejemplo.com', 'Consulta sobre instalación de alarmas de seguridad.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Raúl', 'Morales', 'raul.morales@ejemplo.com', 'Necesito un servicio de mantenimiento para mis sistemas de leds.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Sofía', 'Vázquez', 'sofia.vazquez@ejemplo.com', 'Información sobre instalación de cámaras de vigilancia.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Ricardo', 'Mendoza', 'ricardo.mendoza@ejemplo.com', 'Pregunta sobre instalación de sistemas de energía solar.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Lucía', 'Torres', 'lucia.torres@ejemplo.com', 'Asesoría sobre instalación de sistemas de energía renovable.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Manuel', 'Serrano', 'manuel.serrano@ejemplo.com', 'Quiero instalar cableado de red en mi oficina.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Eva', 'Ruiz', 'eva.ruiz@ejemplo.com', 'Necesito una consulta sobre antenas para televisión.');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Antonio', 'Jiménez', 'antonio.jimenez@ejemplo.com', 'Presupuesto para instalación de iluminación RGB en jardines.');INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Salamanca Sola', 'adritela55@gmail.com', 'fseeeeeeeeeeeeeee');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Salamanca Sola', 'adritela55@gmail.com', 'fseeeeeeeeeeeeeee');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Salamanca Sola', 'arodrod0708@g.educaand.es', 'ff');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'arodrod0708@g.educaand.es', 'dada');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'arodrod0708@g.educaand.es', 'dada');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Salamanca Sola', 'arodrod0708@g.educaand.es', 'dsadas');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('aa', 'aaa', 'aa@gmail.com', 'adwdw');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
INSERT INTO contacto (nombre, apellidos, email, mensaje) VALUES ('Adrián', 'Rodríguez', 'adritela55@gmail.com', 'adad');
